routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Route::name('dashboard.')->prefix('/dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
});

Route::name('user.')->prefix('/user')->middleware('auth')->group(function () {
    Route::get('/', 'UserController@list')->name('list');

    Route::get('/add', 'UserController@add')->name('add');
    Route::post('/add', 'UserController@addSave')->name('add.save');

    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
    Route::post('/edit', 'UserController@editSave')->name('edit.save');

    Route::get('/edit/photo/{id}', 'UserController@editPhoto')->name('edit.photo');
    Route::post('/edit/photo', 'UserController@editPhotoSave')->name('edit.photo.save');

    Route::get('/delete/{id}', 'UserController@delete')->name('delete');
});

Route::name('courses.')->prefix('/courses')->middleware('auth')->group(function () {
    Route::get('/', 'CoursesController@index')->name('list');

    Route::get('/add', 'CoursesController@add')->name('add');
    Route::post('/add/save', 'CoursesController@addSave')->name('add.save');
    Route::get('/edit/{id}', 'CoursesController@edit')->name('edit');
    Route::post('/edit/', 'CoursesController@editSave')->name('edit.save');
    Route::get('/edit/header/{id}', 'CoursesController@editHeader')->name('edit.header');
    Route::post('/edit/header', 'CoursesController@editHeaderSave')->name('edit.header.save');
    Route::get('/delete/{id}', 'CoursesController@delete')->name('delete');

    Route::get('/modules', 'ModulesController@index')->name('modules');
    Route::get('/modules/{course_id}', 'ModulesController@modulesList')->name('modules.list');
    Route::get('/module/add/{course_id}', 'ModulesController@add')->name('module.add');
    Route::post('/module/add/save', 'ModulesController@addSave')->name('module.add.save');
    Route::get('/module/edit/{id}', 'ModulesController@edit')->name('module.edit');
    Route::post('/module/edit/save', 'ModulesController@editSave')->name('module.edit.save');
    Route::get('/module/{course_id}/delete/{id}', 'ModulesController@delete')->name('module.delete');

    Route::get('/exams', 'ExamsController@index')->name('exams');
    Route::get('/exam/{course_id}', 'ExamsController@questions')->name('exam');
    Route::get('/exam/{course_id}/add', 'ExamsController@questionAdd')->name('exam.question.add');
    Route::post('/exam/question/add', 'ExamsController@questionAddSave')->name('exam.question.add.save');
    Route::get('/exam/{course_id}/question/delete/{id}', 'ExamsController@questionDelete')->name('exam.question.delete');
    Route::get('/exam/question/edit/{id}', 'ExamsController@questionEdit')->name('exam.question.edit');
    Route::post('/exam/question/edit-save', 'ExamsController@questionEditSave')->name('exam.question.edit.save');
});

Auth::routes();

Route::post('/login/pengajar', 'Auth\LoginController@loginPengajar')->name('login.pengajar');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Exam;
use App\Module;
use App\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index() {
        $data['usersTotal'] = User::all()->count();
        $data['coursesTotal'] = Course::all()->count();
        $data['modulesTotal'] = Module::all()->count();
        $data['examsTotal'] = Exam::all()->count();
        return view('dashboard.index', $data);
    }
}

resources/views/dashboard/index.blade.php
@extends('template.app')

@section('title', 'Home')

@section('content')
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{$usersTotal}}</h3>

                    <p>Users</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person"></i>
                </div>
                <a href="{{route('user.list')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>{{$coursesTotal}}</h3>

                    <p>Courses</p>
                </div>
                <div class="icon">
                    <i class="ion ion-briefcase"></i>
                </div>
                <a href="{{route('courses.list')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>{{$modulesTotal}}</h3>

                    <p>Modules</p>
                </div>
                <div class="icon">
                    <i class="ion ion-ios-book"></i>
                </div>
                <a href="{{route('courses.modules')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>{{$examsTotal}}</h3>

                    <p>Exams</p>
                </div>
                <div class="icon">
                    <i class="ion ion-checkmark-round"></i>
                </div>
                <a href="{{route('courses.exams')}}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
    </div>
    <!-- /.row -->
@stop