routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Route::name('dashboard.')->prefix('/dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
});

Route::name('user.')->prefix('/user')->middleware('auth')->group(function () {
    Route::get('/', 'UserController@list')->name('list');

    Route::get('/add', 'UserController@add')->name('add');
    Route::post('/add', 'UserController@addSave')->name('add.save');

    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
    Route::post('/edit', 'UserController@editSave')->name('edit.save');

    Route::get('/edit/photo/{id}', 'UserController@editPhoto')->name('edit.photo');
    Route::post('/edit/photo', 'UserController@editPhotoSave')->name('edit.photo.save');

    Route::get('/delete/{id}', 'UserController@delete')->name('delete');
});

Route::name('courses.')->prefix('/courses')->middleware('auth')->group(function () {
    Route::get('/', 'CoursesController@index')->name('list');

    Route::get('/add', 'CoursesController@add')->name('add');
    Route::post('/add/save', 'CoursesController@addSave')->name('add.save');
    Route::get('/edit/{id}', 'CoursesController@edit')->name('edit');
    Route::post('/edit/', 'CoursesController@editSave')->name('edit.save');
    Route::get('/edit/header/{id}', 'CoursesController@editHeader')->name('edit.header');
    Route::post('/edit/header', 'CoursesController@editHeaderSave')->name('edit.header.save');
    Route::get('/delete/{id}', 'CoursesController@delete')->name('delete');

    Route::get('/modules', 'ModulesController@index')->name('modules');
    Route::get('/modules/{course_id}', 'ModulesController@modulesList')->name('modules.list');
    Route::get('/module/add/{course_id}', 'ModulesController@add')->name('module.add');
    Route::post('/module/add/save', 'ModulesController@addSave')->name('module.add.save');
    Route::get('/module/edit/{id}', 'ModulesController@edit')->name('module.edit');
    Route::post('/module/edit/save', 'ModulesController@editSave')->name('module.edit.save');
    Route::get('/module/{course_id}/delete/{id}', 'ModulesController@delete')->name('module.delete');

    Route::get('/exams', 'ExamsController@index')->name('exams');
    Route::get('/exam/{course_id}', 'ExamsController@questions')->name('exam');
    Route::get('/exam/{course_id}/add', 'ExamsController@questionAdd')->name('exam.question.add');
    Route::post('/exam/question/add', 'ExamsController@questionAddSave')->name('exam.question.add.save');
    Route::get('/exam/{course_id}/question/delete/{id}', 'ExamsController@questionDelete')->name('exam.question.delete');
    Route::get('/exam/question/edit/{id}', 'ExamsController@questionEdit')->name('exam.question.edit');
    Route::post('/exam/question/edit-save', 'ExamsController@questionEditSave')->name('exam.question.edit.save');
});

Auth::routes();

Route::post('/login/pengajar', 'Auth\LoginController@loginPengajar')->name('login.pengajar');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'photo', 'role', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }

    public function detail() {
        return $this->hasOne('App\UsersDetail');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Course;
use App\Http\Controllers\Controller;
use App\User;
use App\UsersCourse;
use App\UsersDetail;
use App\UsersExam;
use App\UsersModule;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Tymon\JWTAuth\Exceptions\JWTException;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;
use Tymon\JWTAuth\Exceptions\TokenInvalidException;
use Tymon\JWTAuth\Facades\JWTAuth;
use Exception;

class UserController extends Controller
{
    public function takeCourse($course_id, Request $request) {
        $users_courses = new UsersCourse;
        $users_courses->user_id = $request->user()->id;
        $users_courses->course_id = $course_id;
        if (UsersCourse::where('user_id', $request->user()->id)->where('course_id', $course_id)->count() > 0)
            return response()->json(['status' => 'exist']);
        if ($users_courses->save()) {
            return response()->json(['status' => 'success']);
        } else {
            return response()->json(['status' => 'fail']);
        }
    }

    public function courseList(Request $request) {
        $study = strtolower($request->get('study'));
        $like = '%';
        $my_courses = DB::table('users_courses')->where('user_id', $request->user()->id);
        if (in_array($study, array('matematika', 'ipa', 'indonesia', 'inggris'))) {
            $like = '%'.$study;
        }
        return DB::table('courses')
            ->select('courses.id AS id', 'name', 'level', 'study', 'header')
            ->addSelect(DB::raw('(SELECT COUNT(module_id) FROM users_modules WHERE course_id = courses.id AND user_id = my_courses.user_id) AS total_opened_modules'))
            ->addSelect(DB::raw('(SELECT COUNT(course_id) FROM modules WHERE course_id = courses.id) AS total_modules'))
            ->joinSub($my_courses, 'my_courses', 'courses.id', '=', 'my_courses.course_id')
            ->orderBy('my_courses.created_at', 'DESC')
            ->where('study', 'LIKE', $like)
            ->get();
    }

    public function detail() {
        try {
            if (! $user = JWTAuth::parseToken()->authenticate()) {
                return response()->json(['user_not_found'], 404);
            }
        } catch (TokenExpiredException $e) {
            return response()->json(['token_expired'], $e->getStatusCode());
        } catch (TokenInvalidException $e) {
            return response()->json(['token_invalid'], $e->getStatusCode());
        } catch (JWTException $e) {
            return response()->json(['token_absent'], $e->getStatusCode());
        }

        $user_id = $user->id;
        $detail = User::find($user_id)->detail;

        return response()->json(compact(['user', 'detail']));
    }

    public function openModule($course_id, $module_id, Request $request) {
        $users_module = new UsersModule;
        $users_module->user_id = $request->user()->id;
        $users_module->module_id = $module_id;
        $users_module->course_id = $course_id;
        if (UsersModule::where('user_id', $request->user()->id)->where('module_id', $module_id)->count() > 0)
            return response()->json(['status' => 'opened']);
        if ($users_module->save()) {
            return response()->json(['status' => 'success']);
        } else {
            return response()->json(['status' => 'fail']);
        }
    }

    public function courseScore($course_id) {
        $data = UsersExam::where('course_id', $course_id)->get();
        foreach ($data as $d) {
            $d['answers_recap'] = json_decode($d['answers_recap']);
        }
        return $data;
    }

    public function addDetail(Request $request) {
        try {
            $detail = new UsersDetail;
            $detail->user_id = $request->user()->id;
            $detail->tempat_lahir = $request->tempat_lahir;
            $detail->tanggal_lahir = $request->tanggal_lahir;
            $detail->sekolah = $request->sekolah;
            $detail->kelas = $request->kelas;
            $detail->alamat = $request->alamat;
            $detail->kelurahan = $request->kelurahan;
            $detail->kecamatan = $request->kecamatan;
            $detail->kabupaten = $request->kabupaten;
            $detail->provinsi = $request->provinsi;

            $detail->save();
            return ['status' => 'success'];
        } catch (Exception $e) {
            return ['status' => 'fail'];
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function list() {
        $data['users'] = User::all();
        return view('user.list', $data);
    }

    public function add() {
        return view('user.add');
    }

    public function addSave(Request $request) {
        $photo = $request->profile;
        $photoName = $request->username.'.png';

        if ($photo->storeAs('photo_profile', $photoName)) {
            $user = new User;
            $user->name = $request->name;
            $user->username = $request->username;
            $user->email = $request->email;
            $user->photo = $photoName;
            $user->role = $request->role;
            $user->password = Hash::make($request->password);
            $user->save();
        }

        return redirect()->route('user.list');
    }

    public function edit($id) {
        $data['user'] = User::find($id);
        return view('user.edit', $data);
    }

    public function editSave(Request $request) {
        $user = User::find($request->id);
        $user->name = $request->name;
        $user->username = $request->username;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->save();

        return redirect()->route('user.list');
    }

    public function editPhoto($id) {
        $data['user_id'] = $id;
        $data['profile'] = User::find($id)->photo;

        return view('user.profile', $data);
    }

    public function editPhotoSave(Request $request) {
        $user = User::find($request->id);
        $photo = $request->profile;
        $photoName = $user->username.'.png';

        if (!$user->photo) {
            if ($photo->storeAs('photo_profile', $photoName)) {
                $user->photo = $photoName;
                $user->save();
            }
        } else {
            if (Storage::delete('photo_profile/'.$user->photo) && $photo->storeAs('photo_profile', $photoName)) {
                $user->photo = $photoName;
                $user->save();
            }
        }

        return redirect()->route('user.list');
    }

    public function delete($id) {
        $user = User::find($id);
        $filePath = 'photo_profile/'.$user->photo;
        if ($user->photo == null || Storage::delete($filePath)) {
            $user->delete();
        }

        return redirect()->route('user.list');
    }
}

resources/views/user/add.blade.php
@extends('template.app')

@section('title', 'Add Account')

@section('head')
    <style>
        #photoProfile {
            display: none;
            max-height: 300px;
            height: 300px;
        }
    </style>
@stop

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <form id="addForm">
                    {{csrf_field()}}
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Full name</label>
                            <input type="text" class="form-control" id="name" placeholder="Enter full name" name="name"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" placeholder="Enter username"
                                   name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" placeholder="Enter email address"
                                   name="email" required>
                        </div>
                        <div class="form-group">
                            <label>Role</label>
                            <select class="form-control" name="role" required>
                                <option value="" disabled selected>-- Select role --</option>
                                <option value="0">Admin</option>
                                <option value="1">Pengajar</option>
                                <option value="2">Siswa</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" placeholder="Enter password"
                                   name="password" required>
                        </div>
                        <div class="col-6">
                            <img src="{{asset('/img/default-header.png')}}" id="photoProfile" />
                        </div>
                        <div class="form-group mt-2">
                            <label for="profile">Photo profile</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="profile" name="profile" required>
                                    <label class="custom-file-label" for="profile">Choose photo profile</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <a href="{{route('user.list')}}">
                            <button type="button" class="btn btn-danger">Cancel</button>
                        </a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        $(document).ready(() => {
            /*
            Image cropper
             */
            const photoProfile = document.getElementById('photoProfile');
            let cropper;

            const cropImage = (input) => {
                if (input.files && input.files[0]) {
                    const reader = new FileReader();
                    reader.onload = e => {
                        if (cropper) {
                            cropper.replace(e.target.result);
                        } else {
                            photoProfile.style.display = "block";
                            photoProfile.setAttribute('src', e.target.result);
                            cropper = new Cropper(photoProfile, {
                                aspectRatio: 1,
                                viewMode: 2,
                                zoomOnWheel: false,
                                autoCropArea: 1
                            });
                        }

                    };
                    reader.readAsDataURL(input.files[0]);
                }
            };

            $("#profile").change(function () {
                cropImage(this);
            });

            /*
            Form send
             */
            $('#addForm').submit(e => {
                e.preventDefault();
                cropper.getCroppedCanvas({height: 500, width: 500}).toBlob(blob => {
                    const formData = new FormData();
                    formData.set('name', $('[name=name]').val());
                    formData.set('username', $('[name=username]').val());
                    formData.set('email', $('[name=email]').val());
                    formData.append('profile', blob);
                    formData.set('role', $('[name=role]').val());

                    axios({
                        method: 'post',
                        url: "{{route('user.add.save')}}",
                        data: formData,
                        headers: {
                            'Content-Type': 'multipart/form-data',
                        }
                    }).then(res => {
                        window.location.replace("{{route('user.list')}}")
                    }).catch(err => {
                        alert('Add user error');
                        {{--window.location.replace("{{route('user.list')}}")--}}
                    });
                });
            });
        });
    </script>
@stop

resources/views/user/edit.blade.php
@extends('template.app')

@section('title', 'Edit Account')

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <form method="post" action="{{route('user.edit.save')}}">
                    {{csrf_field()}}
                    <input type="text" value="{{$user['id']}}" name="id" hidden>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Full name</label>
                            <input type="text" class="form-control" id="name" value="{{$user['name']}}" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" value="{{$user['username']}}" name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" value="{{$user['email']}}" name="email" required>
                        </div>
                        <div class="form-group">
                            <label>Role</label>
                            <select class="form-control" name="role" required>
                                <option value="" disabled>-- Select role --</option>
                                <option value="0" {{$user['role'] == 0 ? 'selected' : ''}}>Admin</option>
                                <option value="1" {{$user['role'] == 1 ? 'selected' : ''}}>Pengajar</option>
                                <option value="2" {{$user['role'] == 2 ? 'selected' : ''}}>Siswa</option>
                            </select>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <a href="{{route('user.list')}}">
                            <button type="button" class="btn btn-danger">Cancel</button>
                        </a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
@stop

resources/views/user/list.blade.php
@extends('template.app')

@section('title', 'Users')

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-user mr-1"></i>
                    </h3>
                    <div class="card-tools">
                        <ul class="nav nav-pills ml-auto">
                            <li class="nav-item">
                                <a href="{{route('user.add')}}">
                                    <button class="btn btn-success">
                                        <i class="fas fa-plus"></i>
                                        Add
                                    </button>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div><!-- /.card-header -->
                <div class="card-body">
                    <table id="users-table" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Username</th>
                            <th>Role</th>
                            <th>Photo profile</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $u)
                            <tr>
                                <td>{{$u['name']}}</td>
                                <td>{{$u['username']}}</td>
                                <td>{{$u['role']}}</td>
                                <td><a href="{{asset('photo_profile/'.$u['photo'])}}" target="_blank">{{$u['photo']}}</a></td>
                                <td>
                                    <a href="{{route('user.edit', $u['id'])}}">
                                        <button class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></button>
                                    </a>
                                    <a href="{{route('user.edit.photo', $u['id'])}}">
                                        <button class="btn btn-primary btn-sm"><i class="fas fa-image"></i></button>
                                    </a>
                                    <a href="{{route('user.delete', $u['id'])}}">
                                        <button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        $(function () {
            $("#users-table").DataTable();
        });
    </script>
@stop

resources/views/user/profile.blade.php
@extends('template.app')

@section('title', 'Edit Photo Profile')

@section('head')
    <style>
        #photoProfile {
            display: block;
            max-height: 300px;
            height: 300px;
        }
    </style>
@stop

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">

                <form id="editForm">
                    @csrf
                    <input name="id" value="{{$user_id}}" hidden/>
                    <div class="card-body">
                        <div class="col-6">
                            <img src="{{$profile == null ? asset('/img/default-profile.png') : asset('/photo_profile/'.$profile)}}" id="photoProfile">
                        </div>
                        <div class="form-group mt-2">
                            <label for="photo">Photo profile</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="profile" name="profile">
                                    <label class="custom-file-label" for="photo">Choose photo profile</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <a href="{{route('user.list')}}">
                            <button type="button" class="btn btn-danger">Cancel</button>
                        </a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        $(function () {
            /*
            Image croppper
             */
            const photoProfile = document.getElementById('photoProfile');
            const cropper = new Cropper(photoProfile, {
                aspectRatio: 1,
                viewMode: 2,
                zoomOnWheel: false,
                autoCropArea: 1
            });

            const cropImage = input => {
                if (input.files && input.files[0]) {
                    const reader = new FileReader();
                    reader.onload = e => {
                        cropper.replace(e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            };

            $("#profile").change(function () {
                cropImage(this);
            });

            $('#editForm').submit(e => {
                e.preventDefault();
                cropper.getCroppedCanvas({height: 500, width: 500}).toBlob(blob => {
                    const formData = new FormData();
                    formData.set('id', $("[name=id]").val());
                    formData.append('profile', blob);

                    axios({
                        method: 'post',
                        url: "{{route('user.edit.photo.save')}}",
                        data: formData,
                        headers: {
                            'Content-Type': 'multipart/form-data',
                        }
                    }).then(res => {
                        window.location.replace("{{route('user.list')}}")
                    }).catch(err => {
                        alert('Edit photo profile error');
                        {{--window.location.replace("{{route('user.list')}}")--}}
                    });
                });
            });
        })
    </script>
@stop