routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Route::name('dashboard.')->prefix('/dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
});

Route::name('user.')->prefix('/user')->middleware('auth')->group(function () {
    Route::get('/', 'UserController@list')->name('list');

    Route::get('/add', 'UserController@add')->name('add');
    Route::post('/add', 'UserController@addSave')->name('add.save');

    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
    Route::post('/edit', 'UserController@editSave')->name('edit.save');

    Route::get('/edit/photo/{id}', 'UserController@editPhoto')->name('edit.photo');
    Route::post('/edit/photo', 'UserController@editPhotoSave')->name('edit.photo.save');

    Route::get('/delete/{id}', 'UserController@delete')->name('delete');
});

Route::name('courses.')->prefix('/courses')->middleware('auth')->group(function () {
    Route::get('/', 'CoursesController@index')->name('list');

    Route::get('/add', 'CoursesController@add')->name('add');
    Route::post('/add/save', 'CoursesController@addSave')->name('add.save');
    Route::get('/edit/{id}', 'CoursesController@edit')->name('edit');
    Route::post('/edit/', 'CoursesController@editSave')->name('edit.save');
    Route::get('/edit/header/{id}', 'CoursesController@editHeader')->name('edit.header');
    Route::post('/edit/header', 'CoursesController@editHeaderSave')->name('edit.header.save');
    Route::get('/delete/{id}', 'CoursesController@delete')->name('delete');

    Route::get('/modules', 'ModulesController@index')->name('modules');
    Route::get('/modules/{course_id}', 'ModulesController@modulesList')->name('modules.list');
    Route::get('/module/add/{course_id}', 'ModulesController@add')->name('module.add');
    Route::post('/module/add/save', 'ModulesController@addSave')->name('module.add.save');
    Route::get('/module/edit/{id}', 'ModulesController@edit')->name('module.edit');
    Route::post('/module/edit/save', 'ModulesController@editSave')->name('module.edit.save');
    Route::get('/module/{course_id}/delete/{id}', 'ModulesController@delete')->name('module.delete');

    Route::get('/exams', 'ExamsController@index')->name('exams');
    Route::get('/exam/{course_id}', 'ExamsController@questions')->name('exam');
    Route::get('/exam/{course_id}/add', 'ExamsController@questionAdd')->name('exam.question.add');
    Route::post('/exam/question/add', 'ExamsController@questionAddSave')->name('exam.question.add.save');
    Route::get('/exam/{course_id}/question/delete/{id}', 'ExamsController@questionDelete')->name('exam.question.delete');
    Route::get('/exam/question/edit/{id}', 'ExamsController@questionEdit')->name('exam.question.edit');
    Route::post('/exam/question/edit-save', 'ExamsController@questionEditSave')->name('exam.question.edit.save');
});

Auth::routes();

Route::post('/login/pengajar', 'Auth\LoginController@loginPengajar')->name('login.pengajar');

app/Exam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Exam extends Model
{
    //
}

app/Http/Controllers/Api/ExamController.php
<?php

namespace App\Http\Controllers\Api;

use App\Exam;
use App\Http\Controllers\Controller;
use App\UsersExam;
use Illuminate\Http\Request;

class ExamController extends Controller
{
    public function getQuestions($course_id)
    {
        $questions = Exam::select('id', 'question', 'a', 'b', 'c', 'd', 'e')
            ->where('course_id', $course_id)
            ->orderBy('id')
            ->get();

        foreach ($questions as $q) {
            $q->answer = null;
        }

        return $questions;
    }

    public function answerCheck(Request $request)
    {
        $data['total_true'] = 0;
        $data['total_questions'] = count($request->input('answers'));

        # answer check
        foreach ($request->input('answers') as $k => $a) {
            $isTrue = Exam::where('id', $a['id'])->where('answer', $a['answer'])->count();
            if ($isTrue > 0) {
                $answer = true;
                $data['total_true'] += 1;
            } else {
                $answer = false;
            }
            $result[$k] = ['id' => $a['id'], 'answer' => $answer];
        }
        $data['answer'] = $result;

        # save to database
        $users_exams = new UsersExam;
        $users_exams->user_id = $request->user()->id;
        $users_exams->course_id = $request->input('course_id');
        $users_exams->total_true = $data['total_true'];
        $users_exams->total_questions = $data['total_questions'];
        $users_exams->answers_recap = json_encode($data['answer']);

        if ($users_exams->save()) {
            return ['status' => 'success', 'data' => $data];
        } else {
            return ['status' => 'fail'];
        }
    }
}

app/Http/Controllers/ExamsController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Exam;
use Illuminate\Http\Request;

class ExamsController extends Controller
{
    public function index() {
        $data['courses'] = Course::all();

        return view('exams.index', $data);
    }

    public function questions($course_id) {
        $data['questions'] = Exam::where('course_id', '=', $course_id)->orderBy('created_at')->get();
        $data['course_id'] = $course_id;
        return view('exams.questions', $data);
    }

    public function questionAdd($course_id) {
        $data['course_id'] = $course_id;
        return view('exams.question.add', $data);
    }

    public function questionAddSave(Request $request) {
        $question = new Exam;
        $question->course_id = $request->course_id;
        $question->question = $request->question;
        $question->a = $request->a;
        $question->b = $request->b;
        $question->c = $request->c;
        $question->d = $request->d;
        $question->e = $request->e;
        $question->answer = $request->answer;
        $question->save();

        return redirect()->route('courses.exam', $request->course_id);
    }

    public function questionEdit($id) {
        $data['question'] = Exam::find($id);
        return view('exams.question.edit', $data);
    }

    public function questionEditSave(Request $request) {
        $question = Exam::find($request->id);
        $question->question = $request->question;
        $question->a = $request->a;
        $question->b = $request->b;
        $question->c = $request->c;
        $question->d = $request->d;
        $question->e = $request->e;
        $question->answer = $request->answer;
        $question->save();

        return redirect()->route('courses.exam', $request->course_id);
    }

    public function questionDelete($course_id, $id) {
        $question = Exam::find($id)->delete();

        return redirect()->route('courses.exam', $course_id);
    }
}

resources/views/exams/index.blade.php
@extends('template.app')

@section('title', 'Courses list')

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <div class="card-body">
                    <table id="modules-table" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Course name</th>
                            <th>Total questions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($courses as $course)
                            <tr>
                                <td>
                                    <a href="{{route('courses.exam', $course['id'])}}">
                                        {{$course['name']}}
                                    </a>
                                </td>
                                <td>{{\App\Exam::where('course_id', $course->id)->count()}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div><!-- /.card-body -->
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        $(function () {
            $("#modules-table").DataTable();
        });
    </script>
@stop

resources/views/exams/questions.blade.php
@extends('template.app')

@section('title', 'Questions List')

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-book mr-1"></i>
                    </h3>
                    <div class="card-tools">
                        <ul class="nav nav-pills ml-auto">
                            <li class="nav-item">
                                <a href="{{route('courses.exam.question.add', $course_id)}}">
                                    <button class="btn btn-success">
                                        <i class="fas fa-plus"></i>
                                        Add
                                    </button>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div><!-- /.card-header -->
                <div class="card-body">
                    <table id="questions-table" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>Question</th>
                            <th>Answer</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($questions as $i=>$q)
                            <tr>
                                <td>{{$i+1}}</td>
                                <td>{{$q['question']}}</td>
                                <td>{{$q['answer']}}</td>
                                <td>
                                    <a href="{{route('courses.exam.question.delete', ['course_id'=>$course_id, 'id'=>$q['id']])}}">
                                        <button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                                    </a>
                                    <a href="{{route('courses.exam.question.edit', [$q['id']])}}">
                                        <button class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></button>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div><!-- /.card-body -->
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        $(function () {
            $("#questions-table").DataTable();
        });
    </script>
@stop