routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Route::name('dashboard.')->prefix('/dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController@index')->name('index');
});

Route::name('user.')->prefix('/user')->middleware('auth')->group(function () {
    Route::get('/', 'UserController@list')->name('list');

    Route::get('/add', 'UserController@add')->name('add');
    Route::post('/add', 'UserController@addSave')->name('add.save');

    Route::get('/edit/{id}', 'UserController@edit')->name('edit');
    Route::post('/edit', 'UserController@editSave')->name('edit.save');

    Route::get('/edit/photo/{id}', 'UserController@editPhoto')->name('edit.photo');
    Route::post('/edit/photo', 'UserController@editPhotoSave')->name('edit.photo.save');

    Route::get('/delete/{id}', 'UserController@delete')->name('delete');
});

Route::name('courses.')->prefix('/courses')->middleware('auth')->group(function () {
    Route::get('/', 'CoursesController@index')->name('list');

    Route::get('/add', 'CoursesController@add')->name('add');
    Route::post('/add/save', 'CoursesController@addSave')->name('add.save');
    Route::get('/edit/{id}', 'CoursesController@edit')->name('edit');
    Route::post('/edit/', 'CoursesController@editSave')->name('edit.save');
    Route::get('/edit/header/{id}', 'CoursesController@editHeader')->name('edit.header');
    Route::post('/edit/header', 'CoursesController@editHeaderSave')->name('edit.header.save');
    Route::get('/delete/{id}', 'CoursesController@delete')->name('delete');

    Route::get('/modules', 'ModulesController@index')->name('modules');
    Route::get('/modules/{course_id}', 'ModulesController@modulesList')->name('modules.list');
    Route::get('/module/add/{course_id}', 'ModulesController@add')->name('module.add');
    Route::post('/module/add/save', 'ModulesController@addSave')->name('module.add.save');
    Route::get('/module/edit/{id}', 'ModulesController@edit')->name('module.edit');
    Route::post('/module/edit/save', 'ModulesController@editSave')->name('module.edit.save');
    Route::get('/module/{course_id}/delete/{id}', 'ModulesController@delete')->name('module.delete');

    Route::get('/exams', 'ExamsController@index')->name('exams');
    Route::get('/exam/{course_id}', 'ExamsController@questions')->name('exam');
    Route::get('/exam/{course_id}/add', 'ExamsController@questionAdd')->name('exam.question.add');
    Route::post('/exam/question/add', 'ExamsController@questionAddSave')->name('exam.question.add.save');
    Route::get('/exam/{course_id}/question/delete/{id}', 'ExamsController@questionDelete')->name('exam.question.delete');
    Route::get('/exam/question/edit/{id}', 'ExamsController@questionEdit')->name('exam.question.edit');
    Route::post('/exam/question/edit-save', 'ExamsController@questionEditSave')->name('exam.question.edit.save');
});

Auth::routes();

Route::post('/login/pengajar', 'Auth\LoginController@loginPengajar')->name('login.pengajar');

app/Http/Controllers/CoursesController.php
<?php

namespace App\Http\Controllers;

use App\Exam;
use App\Module;
use Illuminate\Http\Request;
use App\Course;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class CoursesController extends Controller
{
    public function __construct()
    {
        $this->_studies = ['Matematika', 'Bahasa Inggris', 'Bahasa Indonesia', 'IPA'];
    }

    public function index() {
        $data['courses'] = Course::all();
        $data['totalModules'] = DB::table('modules')
            ->selectRaw('course_id, COUNT(course_id) as totalModules')
            ->groupBy('course_id')
            ->get();

        return view('courses.index', $data);
    }

    public function add() {
        $data['studies'] = $this->_studies;
        return view('courses.add', $data);
    }

    public function addSave(Request $request) {
        $photo = $request->header;
        $fileName = 'h-'.time().'.png';

        if ($photo->storeAs('header_photos/', $fileName)) {
            $course = new Course;
            $course->name = $request->name;
            $course->level = $request->level;
            $course->study = $request->study;
            $course->header = $fileName;
            $course->active = 1;
            $course->description = $request->description;
            $course->save();
        }

        return redirect()->route('courses.list');
    }

    public function edit($id) {
        $data['studies'] = $this->_studies;
        $data['course'] = Course::find($id);
        return view('courses.edit', $data);
    }

    public function editSave(Request $request) {
        $course = Course::find($request->id);
        $course->name = $request->name;
        $course->level = $request->level;
        $course->study = $request->study;
        $course->description = $request->description;
        $course->save();

        return redirect()->route('courses.list');
    }

    public function editHeader($id) {
        $data['course_id'] = $id;
        $data['header'] = Course::select('header')->find($id)->header;

        return view('courses.header', $data);
    }

    public function editHeaderSave(Request $request) {
        $course = Course::find($request->id);
        $photo = $request->header;
        $photoName = $course->header;

        if (!$course->header) {
            if ($photo->storeAs('header_photos', $photoName)) {
                $course->header = $photoName;
                $course->save();
            }
        } else {
            if (Storage::delete('header_photos/'.$course->header) && $photo->storeAs('header_photos', $photoName)) {
                $course->header = $photoName;
                $course->save();
            }
        }

        return redirect()->route('courses.list');
    }

    public function delete($id) {
        $course = Course::find($id);
        $modules = Module::where('course_id', $id);
        $exams = Exam::where('course_id', $id);

        $filePath = 'header_photos/'.$course->header;
        if ($course->header == null || Storage::delete($filePath)) {
            $course->delete();
            $modules->delete();
            $exams->delete();
        }

        return redirect()->route('courses.list');
    }

}

resources/views/courses/add.blade.php
@extends('template.app')

@section('title', 'Add Course')

@section('head')
    <style>
        #headerCrop {
            display: none;
            max-height: 300px;
            height: 300px;
        }
    </style>
@stop

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <form id="addForm" method="post">
                    {{csrf_field()}}
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Course name</label>
                            <input type="text" class="form-control" id="name"
                                   placeholder="Enter course name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label>Course level</label>
                            <select class="form-control" name="level" required>
                                <option value="" disabled selected>-- Select level --</option>
                                <option value="1">Kelas 10</option>
                                <option value="2">Kelas 11</option>
                                <option value="3">Kelas 12</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Study name</label>
                            <select class="form-control" name="study" required>
                                <option value="" disabled selected>-- Select study name --</option>
                                @foreach($studies as $s)
                                    <option value="{{$s}}">{{$s}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-6">
                            <img src="{{asset('/img/default-header.png')}}" id="headerCrop" />
                        </div>
                        <div class="form-group mt-2">
                            <label for="header">Header photo</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="header" required>
                                    <label class="custom-file-label" for="header">Choose header</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea required id="description" name="description"></textarea>
                        </div>
                    </div>

                    <div class="card-footer">
                        <a href="{{route('courses.list')}}">
                            <button type="button" class="btn btn-danger">Cancel</button>
                        </a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        $(function () {
            /*
            Image croppper
             */
            const headerCrop = document.getElementById('headerCrop');
            let cropper;

            const cropImage = (input) => {
                if (input.files && input.files[0]) {
                    const reader = new FileReader();
                    reader.onload = e => {
                        if (cropper) {
                            cropper.replace(e.target.result);
                        } else {
                            headerCrop.style.display = "block";
                            headerCrop.setAttribute('src', e.target.result);
                            cropper = new Cropper(headerCrop, {
                                aspectRatio: 2 / 1,
                                viewMode: 2,
                                zoomOnWheel: false
                            });
                        }

                    };
                    reader.readAsDataURL(input.files[0]);
                }
            };

            $("#header").change(function () {
                cropImage(this);
            });

            /*
            Send form
             */
            $('#addForm').submit(e => {
                e.preventDefault();
                cropper.getCroppedCanvas({height: 500, width: 1000}).toBlob(blob => {
                    const formData = new FormData();
                    formData.append('name', $('[name=name]').val());
                    formData.append('level', $('[name=level]').val());
                    formData.append('study', $('[name=study]').val());
                    formData.append('header', blob);
                    formData.append('description', $('[name=description]').val());

                    axios({
                        method: 'post',
                        url: "{{route('courses.add.save')}}",
                        data: formData,
                        headers: {
                            'Content-Type': 'multipart/form-data',
                        }
                    }).then(res => {
                        window.location.replace("{{route('courses.list')}}")
                    }).catch(err => {
                        alert('Add course error');
                        {{--window.location.replace("{{route('courses.list')}}")--}}
                    });
                });
            });
        });

        /*
        CKEditor
         */
        CKEDITOR.replace('description');
    </script>
@stop

resources/views/courses/edit.blade.php
@extends('template.app')

@section('title', 'Edit Course')

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <form method="post" action="{{route('courses.edit.save')}}">
                    {{csrf_field()}}
                    <input type="text" name="id" value="{{$course->id}}" hidden/>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Course Name</label>
                            <input type="text" class="form-control" id="name" value="{{$course['name']}}" name="name" required>
                        </div>
                        <div class="form-group">
                            <label>Course Level</label>
                            <select class="form-control" name="level" required>
                                <option value="" disabled selected>-- Select level --</option>
                                <option value="1" {{$course['level'] == 1 ? 'selected' : ''}}>Kelas 10</option>
                                <option value="2" {{$course['level'] == 2 ? 'selected' : ''}}>Kelas 11</option>
                                <option value="3" {{$course['level'] == 3 ? 'selected' : ''}}>Kelas 12</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Study name</label>
                            <select class="form-control" name="study" required>
                                <option value="" disabled selected>-- Select study name --</option>
                                @foreach($studies as $s)
                                    <option value="{{$s}}" {{$course->study == $s ? "selected" : null}}>{{$s}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea required id="description" name="description">{{$course['description']}}</textarea>
                        </div>
                    </div>

                    <div class="card-footer">
                        <a href="{{route('courses.list')}}">
                            <button type="button" class="btn btn-danger">Cancel</button>
                        </a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        CKEDITOR.replace('description');
    </script>
@stop

resources/views/courses/header.blade.php
@extends('template.app')

@section('head')
    <style>
        #headerCrop {
            display: block;
            max-height: 300px;
            height: 300px;
        }
    </style>
@stop

@section('title', 'Edit Course Header Photo')

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <form id="editForm" method="post">
                    @csrf
                    <input name="id" value="{{$course_id}}" type="text" hidden/>
                    <div class="card-body">
                        <div class="col-6">
                            <img src="{{$header == null ? asset('/img/default-header.png') : asset('/header_photos/'.$header)}}" id="headerCrop">
                        </div>
                        <div class="form-group mt-2">
                            <label for="header">Header photo</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="header" name="header">
                                    <label class="custom-file-label" for="header">Choose header photo</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <a href="{{route('courses.list')}}">
                            <button type="button" class="btn btn-danger">Cancel</button>
                        </a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        $(function () {
            /*
            Image croppper
             */
            const headerCrop = document.getElementById('headerCrop');
            const cropper = new Cropper(headerCrop, {
                aspectRatio: 2 / 1,
                viewMode: 2,
                zoomOnWheel: false,
                autoCropArea: 1
            });

            const cropImage = input => {
                if (input.files && input.files[0]) {
                    const reader = new FileReader();
                    reader.onload = e => {
                        cropper.replace(e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            };

            $("#header").change(function () {
                cropImage(this);
            });

            $('#editForm').submit(e => {
                e.preventDefault();
                cropper.getCroppedCanvas({height: 500, width: 1000}).toBlob(blob => {
                    const formData = new FormData();
                    formData.set('id', $("[name=id]").val());
                    formData.append('header', blob);

                    axios({
                        method: 'post',
                        url: "{{route('courses.edit.header.save')}}",
                        data: formData,
                        headers: {
                            'Content-Type': 'multipart/form-data',
                        }
                    }).then(res => {
                        window.location.replace("{{route('courses.list')}}")
                    }).catch(err => {
                        alert('Edit course header error');
                        {{--window.location.replace("{{route('courses.list')}}")--}}
                    });
                });
            });
        })
    </script>
@stop

resources/views/courses/index.blade.php
@extends('template.app')

@section('title', 'Courses')

@section('content')
    <div class="row">
        <section class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-book mr-1"></i>
                    </h3>
                    <div class="card-tools">
                        <ul class="nav nav-pills ml-auto">
                            <li class="nav-item">
                                <a href="{{route('courses.add')}}">
                                    <button class="btn btn-success">
                                        <i class="fas fa-plus"></i>
                                        Add
                                    </button>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <table id="courses-table" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Course name</th>
                            <th>Course level</th>
                            <th>Header photo</th>
                            <th>Total modules</th>
                            <th>Total questions</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($courses as $course)
                            <tr>
                                <td>{{$course['name']}}</td>
                                <td>{{$course['level']}}</td>
                                <td><a target="_blank" href="{{asset('header_photos/'.$course->header)}}">{{$course->header}}</a></td>
                                <td>
                                    <a href="{{route('courses.modules.list', $course->id)}}">
                                        {{\App\Module::where('course_id', $course->id)->count()}}
                                    </a>
                                </td>
                                <td>
                                    <a href="{{route('courses.exam', $course->id)}}">
                                        {{\App\Exam::where('course_id', $course->id)->count()}}
                                    </a>
                                </td>
                                <td>
                                    <a href="{{route('courses.edit', $course['id'])}}">
                                        <button class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></button>
                                    </a>
                                    <a href="{{route('courses.edit.header', $course['id'])}}">
                                        <button class="btn btn-primary btn-sm"><i class="fas fa-image"></i></button>
                                    </a>
                                    <a href="{{route('courses.delete', $course['id'])}}">
                                        <button class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div><!-- /.card-body -->
            </div>
        </section>
    </div>
@stop

@section('javascript')
    <script>
        $(function () {
            $("#courses-table").DataTable();
        });
    </script>
@stop